name: build

on:
  pull_request:
    branches: 'master'
  push:
    branches: 'master'
    tags: '*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=version::0.0.0
          fi
        shell: bash
      -
        # https://github.com/actions/setup-go
        name: Set up Go
        uses: actions/setup-go@master
        with:
          go-version: 1.12.10
      -
        name: Set GOPATH
        # temporary fix (see https://github.com/actions/setup-go/issues/14)
        run: |
          echo "##[set-env name=GOPATH;]$(dirname $GITHUB_WORKSPACE)"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin"
          echo "##[add-path]$(dirname $GITHUB_WORKSPACE)/bin/windows_386"
        shell: bash
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v1
      -
        # https://github.com/crazy-max/ghaction-mage
        name: Mage build
        uses: crazy-max/ghaction-mage@v1
        with:
          version: latest
          args: build
      -
        # https://github.com/svenstaro/upx-action
        name: UPX compress
        uses: svenstaro/upx-action@v1-release
        if: success()
        with:
          file: bin/WindowsSpyBlocker.exe
          args: -fq
          strip: false
      -
        # https://github.com/crazy-max/ghaction-mage
        name: Mage chocoPack
        uses: crazy-max/ghaction-mage@v1
        if: success()
        with:
          version: latest
          args: chocoPack
      -
        # https://github.com/softprops/action-gh-release
        name: GitHub Release
        uses: softprops/action-gh-release@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            bin/WindowsSpyBlocker.exe
            bin/windowsspyblocker.${{ steps.prepare.outputs.version }}.nupkg
          name: ${{ steps.prepare.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        # https://github.com/crazy-max/ghaction-mage
        name: Mage chocoPush
        uses: crazy-max/ghaction-mage@v1
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
        with:
          version: latest
          args: chocoPush
